#----------------------------------------------------------------------
# This file was generated by C:\Documents and Settings\New User\Desktop\Twirlpaper\code-client\encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

GrayOrangeStar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXVJ"
    "REFUOI2lkD1IA0EQhb+NghKTRlS4ICf+RJBAEAsLQfAgNkFILQQtLGzSC2JhZWsT7CyMQjpt"
    "0oqCIGIhiNgEo3iEW0SbsBJiYc7iyMlGT1CnWdh535uZJ0Sog/9U6KemXbLcctFy/2wAMJbO"
    "0XRWAk0CDeyS5faaUeqPe9CT/t0GdslyGwrCQ8uEE4dUz/IEnSJaIdqlT8HpeYXs2jZEMkgp"
    "MQwDdgR3fSm6o57GXDgRAGJ/Y9idmxllcDYHkYzmLqUEwDiK+X+qAdJMAnB5rQgtbdni9Lzi"
    "3fq06oNB8OsbPry0ZQv/hHLRcmOJKOG+fmRzMxBW8aQPayGOL54I51ZRf3nGcZwvMMD7ZEqD"
    "tRBbVVg33azx8O3aKp4k3DPgB6htANB0VnxYNXQ40uW9DaXN0w2qV/deiDUPrE2kUPEkka5P"
    "o4ubimbQSVvJmvce14fJTo0AIxzkvbHT7eL2DArrpguQzc0Tiu2KdnGr/2OIv60PmxCgU51j"
    "r6AAAAAASUVORK5CYII=")
getGrayOrangeStarData = GrayOrangeStar.GetData
getGrayOrangeStarImage = GrayOrangeStar.GetImage
getGrayOrangeStarBitmap = GrayOrangeStar.GetBitmap
getGrayOrangeStarIcon = GrayOrangeStar.GetIcon

#----------------------------------------------------------------------
GrayStar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZNJ"
    "REFUOI2lkzFIG2EUx39fdJDTW4ISTuSkKs2Qxa6BQm7IIkKgU4Wgg2ugY0WCOIhrQVwcOtQO"
    "dnJJoKMFQcrBlYYiQkChR/g+iG5HjmTJ1yEk5qInVN/0Pt77/7733vc9IRJjvMQSTwX9qqPr"
    "J45+NgBgaaVEV27GQmIBftXRSdsk/PsFJlf+rwK/6uh2AMb8BkbmlMb5IXGtiP4Q/ep9wo+L"
    "a4ofP8FUAaUUlmXR+J6nHcCE2cuxV88EgPhafqVz2UXm3pZgqhChK6UGvmVZAFQqFdKdMgBu"
    "LehVcLxt63fvlzGmZyB1FBECSCkjfrpTxq0FrO/7YtBC/cTRsxkTY3oG1d19VJxqbhG2mgNx"
    "ZIiv186EvAwI724jolEbFkcAfcjpt9+P3u55HmGrSS67GAGODx+6clOHd7dctaOA/kvQgXZA"
    "PKDx64akbeJ5HlJK3owfELaaYO2hlCKdhJ9/ruMB0Ps8uasdXDdgrpQHFnAPP2AAJM0HMxHD"
    "23i8bWuAYilPYvazGE3ux4eHKF66zv8ADvSlecAQiqcAAAAASUVORK5CYII=")
getGrayStarData = GrayStar.GetData
getGrayStarImage = GrayStar.GetImage
getGrayStarBitmap = GrayStar.GetBitmap
getGrayStarIcon = GrayStar.GetIcon

#----------------------------------------------------------------------
Help = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZlJ"
    "REFUOI2lkj0vQ3EUxn+32iq9CU1Qg9eOLBJRg1FCvUwMBmkkJAbfwE4kBjZfQLDVIJQYDEpS"
    "L4lIVBMhgoQ24Sr3NuVKrqG5N/23FRJn+b+c8zznyTmPJNlK+E/Yf0ocxJJG7rurpUYqVifl"
    "KziIJQ2P7ChKeptQ6e+oF4gEgq3je6PJK6OoOkuhqACeGurEIzs4vnpjrLtRKiAoBl6e7gMg"
    "OBcGYLS3jSavTCSmMBnwSQA2k8kEb57cCeDce+QygaLqtDbIVs5mdge4uFMF2cG5sNUdIPWe"
    "Jhp/wiM7WAidGxbBw7OeHVLyhdR7WpCdqwTg+vFVOG0AalrsXOmpKDqDjKZZNeZd8EGV7LQU"
    "uJx2Qb7LaSfz+YW3thxF1XG53UDeFircpazuxcloGpnPrwIFkN3Es/JGsKdV3ELkMgHAgL/Z"
    "Ys+PgN8HwPbRjfUnGGliPmyMD7aT0j5Y2TkTwKO9bQAsrh2yuzBSaCSrcGbDCPh9+OqqMS2t"
    "qDrR+BP7p1eszw7/bOV8ouRLdqBymb0A+CvBX+Mb/Mmp68QJt/oAAAAASUVORK5CYII=")
getHelpData = Help.GetData
getHelpImage = Help.GetImage
getHelpBitmap = Help.GetBitmap
getHelpIcon = Help.GetIcon

#----------------------------------------------------------------------
Info = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAbtJ"
    "REFUOI2lkz9oE2EYxn93aYRCrykh0Ntsly4KcXVLY0YxEgdrnA6Ji9yijlmE0LkYXEpMBEWs"
    "NqW1Lv7Bhoo3B3HKkEZJ4YSkJL2WUlL6OpRLe2kCQZ/te1+e5/3e53s+RVF9/A9GBjWSmaIA"
    "1DoTTPlbvE7fUoYScInxWBQ9pAFgNxygKLXOBNaTax4h5ewKyUxRZiMRZvQAdsNh9+i425vR"
    "A1TsNi/efuP705unIorqQ1F93J1flZzVks2qSM5qSTiVFxfhVF7Cqbys/9iXnNWSGw/fictT"
    "z17HnZItrPT1JZ1dYnLMzy/H8a6QzBQlHouye3Q8kOzCNBKMj6i8evOR9YU5RYUTp/WQdo5c"
    "XjQoLxqeWrawgh7SaNbrAN4V/gUqwF69it1wMI3EUKSK3SYYGD05uG6GU3nZrJ463gu33vsK"
    "3SBd1DQqdpuMeZt0dokr9wvnJptGgo1SicPmdrfmCdLVOwWZvjROPBZl7ctXfm7tAHB5Oshs"
    "JMJGqUStvIW1/FjpKwBw/d4z+c0FTCPB5JgfgD97Hd4vf+awuc2nl48GR7lXaKd9AEAwMMqH"
    "5w/6fqaBAsPiLychyniwVdraAAAAAElFTkSuQmCC")
getInfoData = Info.GetData
getInfoImage = Info.GetImage
getInfoBitmap = Info.GetBitmap
getInfoIcon = Info.GetIcon

#----------------------------------------------------------------------
Link = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAihJ"
    "REFUOI1tk09IVFEUxn/3jRPUoOGioGk56ougbCaIx+g2xjcLN0G7oT9PSCFk3Ai2UGTAITcz"
    "i0KEeaDUsk0uRqXQFjUFwTx0MTjWLDMIYqjhqWlyWwzv+kY7cOCewz3fd8537hVCC3DSCpV5"
    "2ajX+HLmt8rFQlGGrj4SJ+8KP0ChMi/LrkMsFMXSgzjb14n2RAGwqwXKrkP3QQdjfbPiFEDu"
    "w7hs74wQEzcVoFfst/ynCfZ24cntJojmMbd3RrD0INGezVNFfksbWc6eg5k34xKgDaDsOjyP"
    "3fIxbwL3VDy6LtW5N2xjGUGsl+vNEeytggSw9CB29RBLH8LZdlT7XnFv2KbsOkrQRr3G3i60"
    "Neo10sYV7OphS6t+1qPzj1n8E4K2ENf+uvz4VuPi5Qiv3hbQvFU16jXF4BevN2wT+PVMxfsV"
    "l68737H0IEoDoGXnfvaNHQuAGz+fAuDyoKVTBdB90EHayDK6Ljl4lwdgMK6zVKq2FNyJ32Wp"
    "VKW4eoEZQOQ/Tsj2zgjQ3MbR6y4G4zpmwlRFI1NNwLnptMotry6THEiijfXNitLn91h6kP2K"
    "C4CZMBFCKB+M6wAqHpnKYyZMhidzzYfUFb5Edm0LO7VwrMOapD9jIKXETJjMTacprhTpzxgc"
    "dm8czyS0AEILYL24LwEJSCmlBGR/xlA5z72cd6flMz1cTEk7tUBxpdgiXHIgyfBkTo3iz6sO"
    "/P4/Vn+HngstwD++Kt/BGiT6TgAAAABJRU5ErkJggg==")
getLinkData = Link.GetData
getLinkImage = Link.GetImage
getLinkBitmap = Link.GetBitmap
getLinkIcon = Link.GetIcon

#----------------------------------------------------------------------
Twirl = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAgklE"
    "QVQokY1SwRHAIAgLnnt0FTer3ayj2EnsgztEFE5eIEkIKrVaoOK6XwDfMx3qyAGaS8NPnpKg"
    "OZfSJXgSLkFsmH02BG2d0e4OweUMgl5ODzFLS55X9BY3WdKNwBW3qPc91FMZhFheVJKpYwIA"
    "arWsuHWUYIh/64k2RxLJk1cD8APWHUAWq2qq7QAAAABJRU5ErkJggg==")
getTwirlData = Twirl.GetData
getTwirlImage = Twirl.GetImage
getTwirlBitmap = Twirl.GetBitmap
getTwirlIcon = Twirl.GetIcon

#----------------------------------------------------------------------
User = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXdJ"
    "REFUOI2NUkFLAkEYfbt2CEkKwVMXbxaepJ+gF6FLdAmv3rpHQXixW3atQxLSoVtQCCVs0SmU"
    "NJP1Ep3WUktbkmxjs0Knwzbj7s5KPRhmmPne+7753icIogtOSKbzhJ6Vlo5MIiI4Bgqii1sb"
    "e1dErhMGuU5IPFUgTrGOZDPkurFOb97I/JrEiYiOZf2i2hiep30ex5ixv4gA0FS1/wsoLd1C"
    "pNmbqgbl4YkT4L6QSUSE9e0zroKVrSP43T1OQLDbaLYPAGqdAfxeI49UauNyd8Fqp7mj8VSB"
    "2EEdoHswtk8cXUim82QxHGTC1Ya1mVmpCABYCs8gENlhVTKBWmeAaMiDXEXj/klRrtwCAB4/"
    "+uzO0sRqwwgyZ6ZO0CR2MAHyNewwJZnJo8AEnrVvZKUi5kKzI4P9XtGo4nM4K0zgZDMqKC0d"
    "h7kye7RPn1Rq4/jiHtr1KrOSm4NA7ID4JtyYnBpH97UH9V2H+gL4+l0AwN35smUOfgD3Z9HI"
    "8Bv9EgAAAABJRU5ErkJggg==")
getUserData = User.GetData
getUserImage = User.GetImage
getUserBitmap = User.GetBitmap
getUserIcon = User.GetIcon

#----------------------------------------------------------------------
Tag = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXxJ"
    "REFUOI2Nkr9OwlAUxr976wOwGUdYTHFyIZq48wQO0GdQX8A/RUbUPoXaMjKYC6tJoV0VF6JN"
    "xBCIhFaNCQmW40DaQNoCX3KTO9zzu98532FCCMKcPM8L74WiwrBKQgiKk2VZpOs6MS5h2eEB"
    "yLZtGIYB27YBALlcDul0Gvd3t5T4OwAeWHYcB4WiwlzXxeDtZW1I6CB46HkeNjNZjLodDJvV"
    "EHJzfRUP0XU90n//tU39WoX6tQp9mgYREQkhSNO0yEx40H+gUbcDtB8gMR8S8+EP3zFsVpHP"
    "5yHLcsQJLxQV5jhOCJl8DxYcroJwYJZ3ANncOQAye/BJWgq5OD+jhSEWigozTTMRMh1/YfLx"
    "FJmhxFjIQL3RKGWzsso5x/buPn7/piC3B3/8AwDYOiyjXq+j1WqhdFmebWncdmmaRpZlzRJ5"
    "fqRe9TRMQlXVhSQSV1RV1RCSVMy4hI3Y5QACiwQArusu2p4TY1yKFM/r5PiIUqlUbPFagFX6"
    "BwccDX799YXyAAAAAElFTkSuQmCC")
getTagData = Tag.GetData
getTagImage = Tag.GetImage
getTagBitmap = Tag.GetBitmap
getTagIcon = Tag.GetIcon

#----------------------------------------------------------------------
Wrench = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAASFJ"
    "REFUOI2lkr1OwzAURo/diAVVLEggxBwxpo/AE1DRd6A1Up4DdkshzQIbEz9PEIYuSCwsCFQk"
    "pqgqbChrVTOkDoEYNRWfZMn29fl8r6+FkC2aaNA/MnYeDxNRBoRsLR1KKWOllDLVmNfk5iiK"
    "yPOcNE1r8aUGAHmek2VZmX61nEYGVd1cXxkA3/fRWiObQPZ2K9/3y7lwdWEeHxg+Jxy/dQjD"
    "0GmqtSYeJqJWgoXZ2CHqvPO8OPxbtpWeE+6eFBt3mu3RKbD+s/cVSSf8OirGfkh7TRKJM2cZ"
    "pUENzh6L6HSM93ABQe9PA2GSwzq8G0B7Cy77EPSQg1tn+kUG/4C/32A6LlYrwgBytrkH9+cF"
    "uCIMi480j7uGyRN8vKwEA3wBYd2Kw2xkKIkAAAAASUVORK5CYII=")
getWrenchData = Wrench.GetData
getWrenchImage = Wrench.GetImage
getWrenchBitmap = Wrench.GetBitmap
getWrenchIcon = Wrench.GetIcon

#----------------------------------------------------------------------
YellowStar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXJJ"
    "REFUOI2lkzFIw1AQhr8XHWqlDqV1EKloJTiKkwiCGVzEyUlBdHDtLhTnri6uDupgp07dLQhF"
    "OkiLiCBEMJQOaQloyGumxqGk9okRtTcd3H/f+++4J4Q2xiih/VS0ykbwfG0E/wYALG7l6LWO"
    "IiGRAKtsBMlMAvl6AZNbf3NglY3AdyE+dwhA8/aMqFFEuESr/CmoVE32j0+Rrxf478/EpnQc"
    "y8V3IZboazLbNwJAXJ3MBxtrWWbXcwo5bA4jNqUD4Fgu0rMBqDXcvoPLfCbY2V0mnkojO22l"
    "EaDnvA1yX1tCeja1hstBwRIawEHBEq1HF9lpE0+lf92sLFHfuxlAQrvfxXCzAgghpWL929ed"
    "bhLp2WysZRXguGK3dRTITluxDCA9m+SEg9NN4ruqI8VB8/5lkIdjSM8mPjk9gN09mNEA6B9P"
    "88mkVKwzu7KAvr5KpWpSqZpfpcDQIQFc5jMBwH5uE23mXHwVh/XhJYpRv/MHOPOmXOsW/gYA"
    "AAAASUVORK5CYII=")
getYellowStarData = YellowStar.GetData
getYellowStarImage = YellowStar.GetImage
getYellowStarBitmap = YellowStar.GetBitmap
getYellowStarIcon = YellowStar.GetIcon

#----------------------------------------------------------------------
YellowOrangeStar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXVJ"
    "REFUOI2lkT9IAnEUxz9ngXJWQ2iQxIX2ByKQaGgIgg5siaamBrGh1T2QZteW1oYsaHRxjZRA"
    "oqGIcJEsPEQHW+wXx7X0azg8uTOjP2958Hvv833vfX+K4hviP+H7rmgUdFk91+WfBQBmN9N8"
    "NPcGigwUMAq6HNdGMesnENz83QZGQZeWAHV6F4DG1RGDTlG6JhqFXkOxXCO5f4hZP8F6rRIY"
    "m0ct5XkMJQiM2j3a1qUCoJweROX66gxTa2mXchcGGL+rOO/CgpYWB+DmXtgb5DKa3N5ZQg2F"
    "MV/aDvgV/PYOYi7Ozb0glTUUH0AqayjNisB8aaOGwj+GXR4AVM91GVm0j1RLeRcM0FlIUCzX"
    "HLhPACCX0WRy8rlvMtjT1eCEYyB4vvGjuefAwnLDI347W8I1zy3QuH0CoNWxwc5CAjEXZ8Tf"
    "E7p+qLkEhvFEq2PnCzNKcjkGxDg7sseueJu9HuQymgRIpjfwRY4Vb3O3/q2Jv41Po4yfqSxE"
    "vMEAAAAASUVORK5CYII=")
getYellowOrangeStarData = YellowOrangeStar.GetData
getYellowOrangeStarImage = YellowOrangeStar.GetImage
getYellowOrangeStarBitmap = YellowOrangeStar.GetBitmap
getYellowOrangeStarIcon = YellowOrangeStar.GetIcon

#----------------------------------------------------------------------
SplashBMP = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAW8AAAEyCAIAAAC6TsZqAAAAA3NCSVQICAjb4U/gAAAWWklE"
    "QVR4nO3dX2gcd2LA8d+W0JbrEbt1Kq5JTs7F6Qq3BtmOySlnOMcy5CHpKi85agX8FoU1JOBw"
    "7kNAQjERSR9kWuiDhSPoQ1pkWr9EWwI9kNXcXWLXxLG2TjAWDrHkxj2bhGrL3WGOwPZhrPFv"
    "f7OzO39+M/P7/eb7QQ/WerU7uzvz3d/8ZrSqtNttAQCp/V7RCwDAEdQEgB7UBIAe1ASAHtQE"
    "gB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe"
    "1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQE"
    "gB7UBIAe1ASAHtQEgB4PFL0AJqjkci/t7O+iksu9AN1FrEk+25vb8nkO494L9YE2PWpCQcog"
    "+qtMd9BHpc1KgrRYhyAE8ybQoccAh9CUCMd0kKkKu8zlQU2QA4JSCtQE+SAo7ivbvEnWu/Fs"
    "Mz1wOozjgsd0eL3dY1rjWMfc5NWEVxeePLvDWueaSpsTThBJRqFh9XNH2eZNkFiPzT5NaDgZ"
    "1x0c00F67bx+p9G0CSB0oCbQJZ+xA0ExFzWBRrkFhaaYiJpAr9xmNwiKcagJtMtnGkUwSDEN"
    "NUFG8mwKjEBNkKncDvegeJxvghxED0riLvBLQMVjbAKjpBnLMEIpGDWBgQiKlagJzJTbJC60"
    "oSYwWYKgMDwpDDWB4RikWIOawAqxgsLwpBjUBLZghGI6agKL5HDeCpKjJrALIxRzURNYJ2JQ"
    "GJ7kjZrAYQQlV9QENmICxUTUBM4jKDnhd4jdcuJgVrc8vZzVLSfUjpMJfsM4D/w9nYJkt9nn"
    "wJSyxB10sKpni5rkzuqOyIxoCkExCDXJkTMd8RUflARzIqzwWaEm2XMvIoqCm0JQTEFNMuN8"
    "RBRFNoWgGIGa6FC2cISxKSis9vpRk5gIR28EpcSoSU8mtyOL7VbL4yUoZUVNQmjsSPEHPhJJ"
    "8wwQlFKiJgF0RJb42bAmKKz/2lCTTrpS4kBHfAQF0VCTTdZPGWQs2fNDUMqEmujoiMMRUSR4"
    "rghKaZS+JnE3j/KEI4xNgxRmZHNV7pr03jAIRxhng1LibUGHEtdE2SRoRyxuBqWs24ImZa2J"
    "vDHQkWQcDEoptwV9SlkTfzOgI6GifViZNQePqUkeylcTUhKq7ybXbVVxKigl2xZ0K1NN6Mh9"
    "6T94WVpt3AlKabaFbJSmJt4aT0d0foC7e0Epx7aQmXLUhJRk9VcgOlceO+ZlCUpWSvD3dMqb"
    "kor0ld1dSJI9ySZ/7APicH1sUq6UFPVnqHSMUERuLxNjk6w4PTZxPyWVXAYgURZDkvgJZ5Bi"
    "OXfHJo6nxMC/hhlYkQydRmFskhVHa+JsSnRFpMeLnuYurAgKNcmKi3s6zg6Yk23n7W5fEa+f"
    "egmZly0T52ri5ilqyaZFkhVBuYW4CEp5uVUTN1fBBB/Skb4j8q3FZXhQej8iAyekrOFQTRz8"
    "teDoQ5I0uydRbjw1R14R9OLKLKybKekh/1dN0+eYGfFhd6Y9t45wYmxSipREn0bNSNw7Ddli"
    "HXmB0IUTNfE5sqYq22FR+QjStBixXiY358LcZH9NnDqII0+UFDgM6SHW8oTvUBgdFCZiE7K/"
    "Jh5HUuIzLSKyIoICG1g+C5vxOa+ViroxpHy6wm9QHpJYIdVnwXd5Ht58ps9t6HyV+dikTDxQ"
    "1B0H16fo7m2B7uxRx0hJlOetXq8/8cQT+/fv37lz55YtW9ItW5h2nKBE+5TZ7HWrecSrGbH8"
    "hiusJmm5M13irbg6V9a5uTn/30tLS6OjoxpvPClTgoLs2Dlv4k5KPBluZocOHTpz5kw2t00d"
    "0MHOmuSlHZDFnWRwmx3Gx8dXV1ezuW1NM7J5mZyc7Pw27Gq9fgphCqtJcEPtuq2q13jzmf7T"
    "dSUjPz0bGxtLS0u1Wk25zocffljIsgUUHJStW7d2fht2tV4/hTBWjU3cmXbNypYtW0Z/8dZb"
    "j/yPcvkrr7yS2X0WcUobjGTtLKwQR/9tde7Njve6lZWV4eHhjuscPSpPSa6trQ0ODspXWF1d"
    "HRoa8r+t1+unTp3yv+07tx92hWazefbs2ZmZmeCPZOvEQSHE8Pe+G/Zf93Ruuqurq59++ulX"
    "X311/Phx/8LZ2dlHHnlk79691Wq13722W63K1aviyhXx6afCf75rNXHggNizR+zaJQYG/CtH"
    "mo6dOvflzM/X5EsWPvvLw//6uXxJs9m8evWqstiTk5Nbt27ds2fPrl27BqR7RQ7sqUlgYPLc"
    "n//J3Ce35EvW19flmrRaLTklQohms6nU5Nq1ax23+dxz6Zf05MmT8vqdn+hjt81rrrfuvvOL"
    "deVp9PgPoV6vv/7662FNabVa8/PzXR9uoyEaDbF5I0KqdIjpZW/BGte+VlIy+ePth3fdT0Oz"
    "2Zyammr4ty7xCu4v+an+9wptrNrT6TS07TvKJRcvXpS/vXHjhnKFDz74QLlEmZ6UxynJTE1N"
    "hacky1kDKSWtu98q/zn77I7gTzR/9evtf3eha0pkc3NzQ0NDzWazyy00m0eOHImSzs6q93oe"
    "Vr/+7djCZ/Ilteq2t0Z/IMS9x3jmzJndu3d3TUlwyfteBxpZUpNu77rVf/hP5RL5fUkIcfXq"
    "VeUKc3Nzd+7ckS+Rt4RarRZhVN+HsgySnFIihPiXz+8o/7/nz9R9n+avfr177pPo97B7924l"
    "KOvr6xG36uhad789/rMvlAvnX7if+GazOT4+nvj2H3zwwc5vw67W66cQxoaahA/gT58+rVyy"
    "vr7u/7vrgYzPPvus65WFEMFDIfroP0XtPun5WW/dfffSrVcaHQOuWnXb6A/+WPmhqXNfKpfM"
    "Prvj9t/8yDtqdvv27dnZWfVHpqbkb9955x3lCrVabWlJbGyIdlu02+L2bXH+vKjXYzyU2Y9v"
    "Nla/kS9Zqe8b+KPf9789e/as8iNLS0sbGxv+Ua21tbXFxcV6yL3u2LGj89vui6FcviPseuhk"
    "z7yJYnpZCPHUU08pF1+/ft2bGQlOmniWl5f9c0OvX78u/1fw1hJYXFwcHh7unJ3JMiVCVN78"
    "jx7/W6tuk9/bPRdutpSNdvLH23/6o+/73w6c+uufTi9vbGzIQ61Go3HhwoWRkREhRLPZVJ7e"
    "Wq02Pz8/MDDgj8IGBsTAgBgZET/5iTh0qP8DaTQaynTJ4vguZUY5OPR78skn5d8eGBwcHBwc"
    "rNVq9XpdyR+yZsPYJNxjjz2mXHL58mXvH/KkycLCgv/vmZmZVqvl/fuLLzoG1cFbS6BWq+WZ"
    "kt7q+x6ef2FIfm/3fHTz/5RLXvyLP1V/+MTBF198Uf3Bjz7y/qFMUQkhjh07tnkMRX2wo6Pd"
    "fx1Gtrq6OjY2Jl8y++yO2tBDfX5MiCNHjpw5c6bZbCojzeHh4cXFxb4/Do3srsmWLVuU8xT9"
    "eRB50uTw4cPyXoz/X/I+/+TkZAa/IFfkyVqzz+449VfVYEqEEB/e2FAu6XpQ+bEzr6o/uLnz"
    "GJwu2bVrV8IFFUJ0TmAJIer7HpbHSr7gvm2j0RgfH9+9e/f27dsrlcrRo0e9uKRZGCRjd01E"
    "t90T7z3KX++9XWi5JleuXBFCtFoteZM4eFD7qXEFn/f54Y2N4MEdj7KbE2bLH6o7wv4zFqxJ"
    "58kdscdiyg3OfXJrvXU3eLUXXnih9/TW3NycF5ejR48qoxVkzfqaKKerCSFu3bolT5ocOHBA"
    "dEbHOzFUOX6c8q21QN7so3LijBCisfrN7APPiOnle1/GUzLx7iX1jF4hxMDAwPz8fNgkq2xu"
    "bm779u3KITxkyvqaeFNu8iVXrlyRS7Fz504RiI53GqX/ba1W033eZN4fpFatVoN7ATMzM/ff"
    "86Wm1Krbkt2L/1QHBwj+bNSmeI96cnJSOYo08/O1CzdbwWsODAycOnVqZWXl9OnTfQ/Dvf/+"
    "+/K3jz76aOe3aoI3L1e+fbTr1aAwviYRzu9UVqlGoyGXwp9blTe2ixcvfv75/dO0X3rppZSL"
    "2amYz2ScmJgIvmmPjY11DPinl8X08oHH1F9jW/36t8EbDF7oDfTkf/iCZ/fEcvz48Wq1Ks+X"
    "CyHe/kXorsrw8PDExMTi4uLGxsba2trS0lLXuCi/oFStVuVfkgw7vaha9Q5y97kaFMbXJAJl"
    "6qTRaMiTJv7cqny1RqMhH2v0xi+a5HeWWtAbb7wRvPDVV9XJ1P0n/km5pOtMynv/dVv9wav/"
    "LE4cFCcO7t+/X/mvt99+O2y34sIF0fcT47yXSZkvb6x+8+6ljlN1x8bGzp07p/zg4ODg6Ojo"
    "xMTEe++91+dukCUXahKcOvEnTfbu3etfKB8AVub8gregidaBSYRh2uDgYPCwaKPROHnypHzJ"
    "yMiI8jZ+/GdfnPz45p3f/M779s5vfnfy45vK2R+16raR799L88i/vxEcEr788svnzp3zd3la"
    "rY1mU5w8KZ5+uv+D8x07dkz+9pXG6v3p2OnlRqNx6NChsbEx78CN3K9WqxUcH/HRJLnq+jkj"
    "RemyeG8+0/2rU9hKc/78+b5Xm52djbE8/a8gf8W+wVCbDzzKLXR9mMpTsbKy0vUZ62Glvk9+"
    "/oPzvr3Jz0zvR1Hf97D8X/V9D/t3GnuZV1bivF6RFg9hXBibiPDju48//rj87fPPPx+8TnDQ"
    "bpyYn1z52muvBS98+umn5Xfy4eHhWEFZqe+7f07K9LIQolqtJkhSFK+PdMx6zn1y69yX/5vg"
    "dhYWFjIbdaILO2sS2Ki6Ht8NHqnpOj+iFMc48T8jamBgYGlpKXj59PS0/O3w8PDa2lrfo631"
    "fQ+vvT6ipMS/ha6/0dPlRuL8tk71oe8ov/T89+f/2zt3JuKeS71ev3bt2uHDh2PcK1Iz6+/p"
    "RP0zK93eosfGxpTZkNOnT09MTChXm5qaiv4RGIk+Lanju7g3qAqkJPhbOWG30PVjVhYWFg4f"
    "HlcW7N6nJf3jpPz7u7PP7njkwT/Y+73vVh+SPvkhZHDUarUuXbp0+fLl69ev+5NWtVrtwIED"
    "1erxH/5QKMffg5OyHY/ixMHW3W+3/u0v5SucrlUnFq9593Xjxo3g5yRt3l11aGgo7ChM5L+A"
    "0XPxEMKsmqjC3paNOxcr7IhFuue268NP+9h7/t5Q73FQwrvucTgn5mJk8rrHXzyEsHNPpwwy"
    "+RDcfsdpe2yuxhUcxrHwEwmsWa1Ne2eLdiKM/PS69neLkC0La2KcDE5X0z8wSbSQhUSEv0xg"
    "LfZ0yqD4P4vVjWljN6RFTcyj+c05mBI2Y2TC4Jow4tXAzFGJoGhOMrgmpaVttsLYlMBN1ASA"
    "HtQE9mDn12ym1sSa9Ya9iQSYNHGTqTXpwZrQAOViYU1gE8ZuJUJNslPshtTj3otdMHZznGVn"
    "TdjZsQMnzpWLnTVBWoUMT0iJ46hJppg18JES91lbE3Z20sqzdHFSwqcfWMvamkCDTIPi3zij"
    "krIwtSa8QYWxYFBWISXlZGpN3GH4ZylpX7ws/2oq7zFm47PXUmqbOtUafcEq6Tb7bD5hGxYy"
    "eGzCG1F+EgSx0rlHo3AgJQ48hLwxNnFYrHGTxhEW22FJGTw2sUYRG4+5c7GZPRuMVY1ndk1Y"
    "gXo4cTBCU3IuHaOSUjO7JujLlKC0SQmoiZFiDcqK3Otp0xH4bK6JQXMHGWxOOoOS0daezc0a"
    "9LIiHptrYo1cTkjJIyjtzi+Huf3oskJNHJJVUBzOh5lnHtqKmrilf1ASfAGRUBODJTtAbvW8"
    "g9ULX3rUJB9JR9TTy0ma4t42yZlHNqAmNiAosAE1yU26Cb8yB4WBiSWMrwlrkq/MQckVE88J"
    "GV8Ta0RZBVMfjyxhUDJ8O+HwsGbUJGcEJQ5GplahJvkrKCjWNYWU2Mbymli3hdxTRFCEVU8X"
    "KbGQ5TUxS6zZux4fgxhN4qAY2xQjFowp2OSoSbGKCIowZLsNx8DETtREr9zf2ZwJir88pMRa"
    "9tfEtK0itoLmUIQDT10aHB7Wz/6aGCfB8KT0QWFg4gRqkoUiZvLsDUrhC3AfU7CpUJOMxF0v"
    "dQy8k/3CsSj0QI98vwxMLGdDTWxdyYoIikg3SMm5KaTELZV224bRXd+13Oh1MXomtL4WWaQh"
    "zfPcY3nyfvkc/oOnReIvh+Ygtz8w3ml6WX9QTCuUTqQkLRv2dMpF65FLUzbUcKYsISnRwJKa"
    "mLLOJRb3pHt9TH7qTFk2UqKHJTVxQXGrrCkbbSdTloqUaONKTQw6Z0EL3WdqmrLpbipyeeTn"
    "lpToZMkxHRGtF6ZtM13EykQGL03h2S3+NfJfAkvWfHu4VRNhwsraV9FBEQU1xZSXxnv+LVnt"
    "rWJPTYQzQTGgJr2lb425LwEpyRDnm+Qv+uknQvMZKBGZ24KUSEm2XJmFlRU+NdBfcQeMy4uU"
    "ZM7Fmgj3goKUSEkeHK2JaxiepEFKcmJVTWLtz7s2PCEoMJ1VNREEBXExMMmPbTUR7h1xYEXP"
    "DinJlYU1EXGCYsHwJBaGJ9GRkrzZWRPXsL+jHc9SAaytSan3d9hUeuM3cYphbU2Ee0GJhaCE"
    "ISWFsbkmrinoU6mdQkqKZHlNXBueEBQtSEkxLK+JiBAUyw7rEJTEeCoKZn9NorAsKHFV2JDY"
    "xzGBVZ9v0oMjn8zm01UHJ17cUMFnye3Ha7pyjE08No1QdG0VFenLJV0fESkpWJlqIsoZFJ91"
    "WamEfwWRkuKVrCai5EHx9NhKE39lsVTRkRIjlK8mgqBkocAe2fIUua+UNREExRk8OQZx5ZiO"
    "SBoIaw70WDTfkRtXVl1XOFQTkWLEQVPs49B66wq3aiLKEJSgMiTGrbXUUc7VRJQzKD73yuLc"
    "+ukuF2siSh4Uj11ZcXElLB9HayIIShY43x+9uFsTke4wME0BYnL6fJM0RbDphBTACE6PTXwM"
    "UoDslaMmHmZSgCw5vaejSBwF9nqACMo0NvGkTwNDFaCbMo1NPOlbwFAF6KZ8NREEBchEKWsi"
    "hJheZocF0KusNfFwQgqgT/lmYbvi4DGQWrnHJj4OHgOpUZNNjDKAdNjTCRF30EGMUHqMTULE"
    "rQO7PCg9ahKOoABxPFD0ArjFDwo7Pigf5k360T7iIDRwFDWJILddGEIDk/XbEKhJNHnOidAU"
    "FCvp2s68iXlOHCQoyIPu90jGJnEYeNSG7qCvvNZbahKTgUHxuJQVjU9ybk+LsStGjqhJfFas"
    "NxltRVY8dhSEmqTApgVIqEk2CA3KY3MgTE1yR2hgvkR7ytSkIDQFJtA6v0ZNikNQkJtcjm1R"
    "ExvQHURU6IkC1MQq7mVFy9qf89Pi0qk9WlETm2W6FbHNICZqAkAPPnsNgB7UBIAe1ASAHtQE"
    "gB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe"
    "1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQE"
    "gB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe"
    "1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe1ASAHtQEgB7UBIAe/w8k7TLi"
    "lD+PNgAAAABJRU5ErkJggg==")
getSplashBMPData = SplashBMP.GetData
getSplashBMPImage = SplashBMP.GetImage
getSplashBMPBitmap = SplashBMP.GetBitmap
getSplashBMPIcon = SplashBMP.GetIcon

